/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppPurchaseRequisitionsRouteImport } from './routes/_app/purchase-requisitions'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app/purchase-orders'
import { Route as AppItemsRouteImport } from './routes/_app/items'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppGoodsReceiptRouteImport } from './routes/_app/goods-receipt'
import { Route as AppGlAccountsRouteImport } from './routes/_app/gl-accounts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCostCentersRouteImport } from './routes/_app/cost-centers'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRequisitionsRoute = AppPurchaseRequisitionsRouteImport.update({
  id: '/purchase-requisitions',
  path: '/purchase-requisitions',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppGoodsReceiptRoute = AppGoodsReceiptRouteImport.update({
  id: '/goods-receipt',
  path: '/goods-receipt',
  getParentRoute: () => AppRoute,
} as any)
const AppGlAccountsRoute = AppGlAccountsRouteImport.update({
  id: '/gl-accounts',
  path: '/gl-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCostCentersRoute = AppCostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cost-centers': typeof AppCostCentersRoute
  '/dashboard': typeof AppDashboardRoute
  '/gl-accounts': typeof AppGlAccountsRoute
  '/goods-receipt': typeof AppGoodsReceiptRoute
  '/invoices': typeof AppInvoicesRoute
  '/items': typeof AppItemsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/purchase-requisitions': typeof AppPurchaseRequisitionsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/units': typeof AppUnitsRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cost-centers': typeof AppCostCentersRoute
  '/dashboard': typeof AppDashboardRoute
  '/gl-accounts': typeof AppGlAccountsRoute
  '/goods-receipt': typeof AppGoodsReceiptRoute
  '/invoices': typeof AppInvoicesRoute
  '/items': typeof AppItemsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/purchase-requisitions': typeof AppPurchaseRequisitionsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/units': typeof AppUnitsRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/cost-centers': typeof AppCostCentersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gl-accounts': typeof AppGlAccountsRoute
  '/_app/goods-receipt': typeof AppGoodsReceiptRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/items': typeof AppItemsRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/purchase-requisitions': typeof AppPurchaseRequisitionsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/units': typeof AppUnitsRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cost-centers'
    | '/dashboard'
    | '/gl-accounts'
    | '/goods-receipt'
    | '/invoices'
    | '/items'
    | '/purchase-orders'
    | '/purchase-requisitions'
    | '/roles'
    | '/settings'
    | '/suppliers'
    | '/units'
    | '/users'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cost-centers'
    | '/dashboard'
    | '/gl-accounts'
    | '/goods-receipt'
    | '/invoices'
    | '/items'
    | '/purchase-orders'
    | '/purchase-requisitions'
    | '/roles'
    | '/settings'
    | '/suppliers'
    | '/units'
    | '/users'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/cost-centers'
    | '/_app/dashboard'
    | '/_app/gl-accounts'
    | '/_app/goods-receipt'
    | '/_app/invoices'
    | '/_app/items'
    | '/_app/purchase-orders'
    | '/_app/purchase-requisitions'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/units'
    | '/_app/users'
    | '/_auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-requisitions': {
      id: '/_app/purchase-requisitions'
      path: '/purchase-requisitions'
      fullPath: '/purchase-requisitions'
      preLoaderRoute: typeof AppPurchaseRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goods-receipt': {
      id: '/_app/goods-receipt'
      path: '/goods-receipt'
      fullPath: '/goods-receipt'
      preLoaderRoute: typeof AppGoodsReceiptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gl-accounts': {
      id: '/_app/gl-accounts'
      path: '/gl-accounts'
      fullPath: '/gl-accounts'
      preLoaderRoute: typeof AppGlAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cost-centers': {
      id: '/_app/cost-centers'
      path: '/cost-centers'
      fullPath: '/cost-centers'
      preLoaderRoute: typeof AppCostCentersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCostCentersRoute: typeof AppCostCentersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGlAccountsRoute: typeof AppGlAccountsRoute
  AppGoodsReceiptRoute: typeof AppGoodsReceiptRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppItemsRoute: typeof AppItemsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppPurchaseRequisitionsRoute: typeof AppPurchaseRequisitionsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCostCentersRoute: AppCostCentersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGlAccountsRoute: AppGlAccountsRoute,
  AppGoodsReceiptRoute: AppGoodsReceiptRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppItemsRoute: AppItemsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppPurchaseRequisitionsRoute: AppPurchaseRequisitionsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
